[tool.pysen]
version = "0.11"

[tool.pysen.lint]
enable_black = true
enable_flake8 = true
enable_isort = true
enable_mypy = true
mypy_preset = "strict"
line_length = 88
py_version = "py311"
[[tool.pysen.lint.mypy_targets]]
  paths = ["."]


[tool.poetry]
name = "aoirint-mcping-bff"
version = "0.0.0"
description = ""
authors = ["aoirint <aoirint@gmail.com>"]
readme = "README.md"
packages = [{include = "aoirint_mcping_bff"}]

[tool.poetry.dependencies]
python = "~3.11"
fastapi = "^0.111.0"
pydantic = "^2.3.0"
uvicorn = "^0.20.0"
requests = "^2.32.0"

[tool.poetry.group.dev.dependencies]
mypy = "^1.0"
pysen = "^0.11.0"
flake8 = "^6.0.0"
flake8-bugbear = "^23.2.13"
black = "^24.3.0"
isort = "^5.12.0"
types-requests = "^2.28.11.14"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
