[tool.pysen]
version = "0.10"

[tool.pysen.lint]
enable_black = true
enable_flake8 = true
enable_isort = true
enable_mypy = true
mypy_preset = "strict"
line_length = 88
py_version = "py310"
[[tool.pysen.lint.mypy_targets]]
  paths = ["."]


[tool.poetry]
name = "aoirint-mcping-bff"
version = "0.0.0"
description = ""
authors = ["aoirint <aoirint@gmail.com>"]
readme = "README.md"
packages = [{include = "aoirint_mcping_bff"}]

[tool.poetry.dependencies]
python = "~3.10"
fastapi = "^0.92.0"
pydantic = "^1.10.5"
uvicorn = "^0.20.0"
requests = "^2.28.2"
types-requests = "^2.28.11.14"

[tool.poetry.group.dev.dependencies]
mypy = ">=0.900, <1.0"
pysen = "^0.10.3"
flake8 = "^6.0.0"
flake8-bugbear = "^23.2.13"
black = "^23.1.0"
isort = "^5.12.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
